// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameSharingInfo = "sharing_info"

// SharingInfo mapped from table <sharing_info>
type SharingInfo struct {
	ID       string `gorm:"column:id;primaryKey" json:"id"`
	NoteID   string `gorm:"column:note_id;not null" json:"note_id"`
	Editable bool   `gorm:"column:editable;not null" json:"editable"`
}

// TableName SharingInfo's table name
func (*SharingInfo) TableName() string {
	return TableNameSharingInfo
}
