// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           *string `gorm:"column:id;type:TEXT" json:"id"`
	Email        *string `gorm:"column:email;type:TEXT" json:"email"`
	PasswordHash *[]byte `gorm:"column:password_hash;type:BLOB" json:"password_hash"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
